# PyTorch Basics

In this notebook we cover the basics of PyTorch. PyTorch is an open source machine learning framework from Facebook AI Research with a friendly Python API. 

## Installing the package

We use `pip` to install the latest version of PyTorch in this notebook environment

In [1]:
# Install PyTorch
!pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 127.3MB 216kB/s  eta 0:00:017.6MB/s eta 0:00:02███████████████████████▎      | 100.4MB 66.9MB/s eta 0:00:01


In [2]:
import torch

## Tensors 

A Tensor is the instrument for storing data in PyTorch. All operations happen over this basic building block. A tensor is an arbitrary N-dimensional array of numbers. 
For example: a full HD color image could be a read in as a tensor of shape (1920, 1080, 3) where the image is of size 1920x1080 pixels and has 3 color channels (RGB).

### Introduction

In [3]:
# Random 5-by-4 tensor
x = torch.rand(5, 4)
print(x)

tensor([[0.1772, 0.3180, 0.9613, 0.5944],
        [0.5491, 0.9709, 0.2236, 0.0164],
        [0.8696, 0.1982, 0.2581, 0.5308],
        [0.6458, 0.7415, 0.1484, 0.3012],
        [0.8780, 0.7333, 0.2761, 0.4845]])


In [4]:
# Zero 3-by-10 tensor, with a specified integer data type (dtype)
y = torch.zeros(3, 10, dtype=torch.int32)
print(y)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)


In [5]:
# Create tensor directly from a Python list
z = torch.tensor([2.1, 3.5, 2020])
print(z)

tensor([   2.1000,    3.5000, 2020.0000])


In [6]:
# Access properties of a tensor
print(f"Size: {x.size()}")
print(f"Number of elements: {y.numel()}")

Size: torch.Size([5, 4])
Number of elements: 30


### Basic Operations on Tensors

In this section we explore the basic arithmatic operators on small tensors.

In [7]:
x = torch.rand(5, 4)
y = torch.rand(5, 4) + 2
print(f"x: {x}\ny: {y}")

x: tensor([[0.6478, 0.2255, 0.1319, 0.7865],
        [0.4695, 0.9487, 0.8575, 0.1518],
        [0.4144, 0.0450, 0.3357, 0.5459],
        [0.2954, 0.1237, 0.5252, 0.9807],
        [0.9307, 0.8023, 0.8573, 0.2494]])
y: tensor([[2.9413, 2.1250, 2.4527, 2.2269],
        [2.4353, 2.3696, 2.0771, 2.7013],
        [2.3114, 2.6359, 2.2057, 2.1392],
        [2.7394, 2.0340, 2.3726, 2.4831],
        [2.3263, 2.2619, 2.7052, 2.8532]])


In [8]:
# Element-wise operations between tensors
print(f"Addition: {x + y}")
print(f"Subtraction: {x - y}")
print(f"Multiplication: {x * y}")
print(f"Division: {x / y}")

Addition: tensor([[3.5891, 2.3506, 2.5846, 3.0134],
        [2.9047, 3.3183, 2.9347, 2.8531],
        [2.7257, 2.6809, 2.5414, 2.6851],
        [3.0348, 2.1577, 2.8978, 3.4638],
        [3.2570, 3.0643, 3.5624, 3.1026]])
Subtraction: tensor([[-2.2934, -1.8995, -2.3208, -1.4403],
        [-1.9658, -1.4209, -1.2196, -2.5495],
        [-1.8970, -2.5910, -1.8700, -1.5933],
        [-2.4440, -1.9103, -1.8475, -1.5024],
        [-1.3956, -1.4596, -1.8479, -2.6038]])
Multiplication: tensor([[1.9054, 0.4793, 0.3235, 1.7514],
        [1.1433, 2.2480, 1.7812, 0.4101],
        [0.9578, 0.1185, 0.7405, 1.1678],
        [0.8092, 0.2516, 1.2460, 2.4352],
        [2.1652, 1.8148, 2.3190, 0.7117]])
Division: tensor([[0.2203, 0.1061, 0.0538, 0.3532],
        [0.1928, 0.4004, 0.4129, 0.0562],
        [0.1793, 0.0171, 0.1522, 0.2552],
        [0.1078, 0.0608, 0.2213, 0.3950],
        [0.4001, 0.3547, 0.3169, 0.0874]])


In [9]:
# Between a tensor and a scalar
print(f"Addition: {x + 1}")
print(f"Subtraction: {x - 1}")
print(f"Multiplication: {x * 2}")
print(f"Division: {x / y}")

Addition: tensor([[1.6478, 1.2255, 1.1319, 1.7865],
        [1.4695, 1.9487, 1.8575, 1.1518],
        [1.4144, 1.0450, 1.3357, 1.5459],
        [1.2954, 1.1237, 1.5252, 1.9807],
        [1.9307, 1.8023, 1.8573, 1.2494]])
Subtraction: tensor([[-0.3522, -0.7745, -0.8681, -0.2135],
        [-0.5305, -0.0513, -0.1425, -0.8482],
        [-0.5856, -0.9550, -0.6643, -0.4541],
        [-0.7046, -0.8763, -0.4748, -0.0193],
        [-0.0693, -0.1977, -0.1427, -0.7506]])
Multiplication: tensor([[1.2956, 0.4511, 0.2638, 1.5730],
        [0.9389, 1.8974, 1.7151, 0.3036],
        [0.8287, 0.0899, 0.6714, 1.0918],
        [0.5908, 0.2474, 1.0503, 1.9615],
        [1.8615, 1.6047, 1.7145, 0.4989]])
Division: tensor([[0.2203, 0.1061, 0.0538, 0.3532],
        [0.1928, 0.4004, 0.4129, 0.0562],
        [0.1793, 0.0171, 0.1522, 0.2552],
        [0.1078, 0.0608, 0.2213, 0.3950],
        [0.4001, 0.3547, 0.3169, 0.0874]])
